In [0]:
from tensorflow.keras.datasets import boston_housing

(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

57344/57026 [==============================] - 0s 0us/step


In [0]:
X_train.shape

(404, 13)

In [0]:
y_train.shape

(404,)

In [0]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [0]:
y_train[0]

15.2

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model = Sequential()
Model.add(Dense(10, activation = 'relu', input_dim = 13))
Model.add(Dense(1, activation = 'linear'))

In [0]:
Model.compile(loss = 'mse', optimizer = 'rmsprop', metrics = ['mae'])

In [0]:
Model.fit(X_train, y_train, epochs = 20, batch_size = 10, verbose = 0)

In [0]:
Model.history.history

{'loss': [39.27238845825195,
  37.41634750366211,
  37.718292236328125,
  37.84196853637695,
  36.5086555480957,
  38.2685432434082,
  37.42789840698242,
  36.52325439453125,
  37.23429870605469,
  38.00221252441406,
  37.30478286743164,
  36.23823547363281,
  36.85375213623047,
  36.33372497558594,
  35.76197814941406,
  36.29176330566406,
  37.43635559082031,
  35.96790313720703,
  36.45983123779297,
  35.61260986328125],
 'mae': [4.586545467376709,
  4.400282382965088,
  4.52470064163208,
  4.568711280822754,
  4.493928909301758,
  4.510570049285889,
  4.465441703796387,
  4.433210849761963,
  4.419160842895508,
  4.488175868988037,
  4.49423360824585,
  4.431825637817383,
  4.454082012176514,
  4.428360939025879,
  4.3991851806640625,
  4.43087100982666,
  4.573723316192627,
  4.420432090759277,
  4.485056400299072,
  4.338631629943848]}

In [0]:
Model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 499us/step - loss: 39.0817 - mae: 4.8402


[39.081687927246094, 4.8401994705200195]

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model = Sequential()
Model.add(Dense(10, activation = 'relu', input_dim = 13))
Model.add(Dense(5, activation = 'elu'))
Model.add(Dense(1, activation = 'linear'))
Model.compile(loss = 'mse', optimizer = 'rmsprop', metrics = ['mae'])
Model.fit(X_train, y_train, epochs = 100, batch_size = 10, verbose = 0)

In [0]:
Model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 749us/step - loss: 84.8338 - mae: 6.5170


[84.83384704589844, 6.516961097717285]

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model = Sequential()
Model.add(Dense(10, activation = 'relu', input_dim = 13))
Model.add(Dense(5, activation = 'elu'))
Model.add(Dense(1, activation = 'linear'))
Model.compile(loss = 'mse', optimizer = 'sgd', metrics = ['mae'])
Model.fit(X_train, y_train, epochs = 100, batch_size = 10, verbose = 0)

In [0]:
Model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 505us/step - loss: 84.0516 - mae: 6.5208


[84.05158233642578, 6.520772457122803]

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model = Sequential()
Model.add(Dense(10, activation = 'relu', input_dim = 13))
Model.add(Dense(5, activation = 'elu'))
Model.add(Dense(1, activation = 'linear'))
Model.compile(loss = 'mse', optimizer = 'adam', metrics = ['mae'])
Model.fit(X_train, y_train, epochs = 200, batch_size = 10, verbose = 0)

In [0]:
Model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 499us/step - loss: 27.3565 - mae: 4.1078


[27.356460571289062, 4.1078314781188965]

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model = Sequential()
Model.add(Dense(10, activation = 'relu', input_dim = 13))
Model.add(Dense(5, activation = 'elu'))
Model.add(Dense(1, activation = 'linear'))
Model.compile(loss = 'mae', optimizer = 'adam', metrics = ['mse'])
Model.fit(X_train, y_train, epochs = 200, batch_size = 10, verbose = 0)

In [0]:
Model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 748us/step - loss: 4.0899 - mse: 33.7296


[4.089884281158447, 33.72962188720703]

In [0]:
Model.predict(X_test)[0:5]

array([[10.67075 ],
       [20.734966],
       [22.635632],
       [27.783398],
       [25.093555]], dtype=float32)

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Model01 = Sequential([Dense(10, activation = 'relu', input_dim = 13), Dense(1, activation = 'relu')])

In [0]:
Model01.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

Model02 = Sequential()
Model02.add(Dense(10, input_dim = 13))
Model02.add(Activation('relu'))
Model02.add(Dense(1))
Model02.add(Activation('relu'))

In [0]:
Model02.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_23 (Dense)             (None, 10)                140       
_________________________________________________________________
activation_5 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_6 (Activation)    (None, 1)                 0         
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

Model03 = Sequential()
Model03.add(Dense(10, input_dim = 13))
Model03.add(Activation('relu'))
Model03.add(Activation('tanh'))
Model03.add(Dense(1))
Model03.add(Activation('relu'))

In [0]:
Model03.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 10)                140       
_________________________________________________________________
activation_7 (Activation)    (None, 10)                0         
_________________________________________________________________
activation_8 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_9 (Activation)    (None, 1)                 0         
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
Model03.layers

In [0]:
Model03.layers[0].name

'dense_25'

In [0]:
Model03.layers[0](X_train)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



<tf.Tensor: shape=(404, 10), dtype=float32, numpy=
array([[ -37.725937,  -76.89065 ,   11.856559, ...,  204.88133 ,
         172.6218  , -112.69852 ],
       [-100.21447 , -102.60565 ,   23.569439, ...,  222.76778 ,
         151.07535 , -101.69258 ],
       [-192.81467 ,  -64.91379 ,  -56.69866 , ...,  303.27423 ,
         199.46552 , -113.62111 ],
       ...,
       [ -75.91355 ,  -91.137   ,   23.634203, ...,  187.96869 ,
         148.37622 ,  -96.74808 ],
       [ -92.68358 ,  -37.22816 ,  -34.989025, ...,  203.00333 ,
         139.25545 ,  -75.54098 ],
       [ -63.23234 ,  -98.37905 ,   33.17447 , ...,  188.19185 ,
         140.11874 ,  -96.755035]], dtype=float32)>

In [0]:
Current_config = Model03.get_config()

In [0]:
from tensorflow.keras.models import Sequential

Model04 = Sequential.from_config(Current_config)

In [0]:
Model04.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 10)                140       
_________________________________________________________________
activation_7 (Activation)    (None, 10)                0         
_________________________________________________________________
activation_8 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_9 (Activation)    (None, 1)                 0         
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
Current_config_json = Model03.to_json()

In [0]:
from tensorflow.keras.models import model_from_json

Model05 = model_from_json(Current_config_json)

In [0]:
Model05.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 10)                140       
_________________________________________________________________
activation_7 (Activation)    (None, 10)                0         
_________________________________________________________________
activation_8 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_9 (Activation)    (None, 1)                 0         
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
print(Current_config_json)

{"class_name": "Sequential", "config": {"name": "sequential_10", "layers": [{"class_name": "Dense", "config": {"name": "dense_25", "trainable": true, "batch_input_shape": [null, 13], "dtype": "float32", "units": 10, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Activation", "config": {"name": "activation_7", "trainable": true, "dtype": "float32", "activation": "relu"}}, {"class_name": "Activation", "config": {"name": "activation_8", "trainable": true, "dtype": "float32", "activation": "tanh"}}, {"class_name": "Dense", "config": {"name": "dense_26", "trainable": true, "dtype": "float32", "units": 1, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config"

In [0]:
with open('model03.config', 'w') as f:
    f.write(Current_config_json)

In [0]:
with open('model03.config', 'r') as f:
    Config = f.read()

In [0]:
print(Config)

{"class_name": "Sequential", "config": {"name": "sequential_10", "layers": [{"class_name": "Dense", "config": {"name": "dense_25", "trainable": true, "batch_input_shape": [null, 13], "dtype": "float32", "units": 10, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Activation", "config": {"name": "activation_7", "trainable": true, "dtype": "float32", "activation": "relu"}}, {"class_name": "Activation", "config": {"name": "activation_8", "trainable": true, "dtype": "float32", "activation": "tanh"}}, {"class_name": "Dense", "config": {"name": "dense_26", "trainable": true, "dtype": "float32", "units": 1, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config"

In [0]:
from tensorflow.keras.models import model_from_json

Model06 = model_from_json(Config)

In [0]:
Model06.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 10)                140       
_________________________________________________________________
activation_7 (Activation)    (None, 10)                0         
_________________________________________________________________
activation_8 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_9 (Activation)    (None, 1)                 0         
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [0]:
from tensorflow.keras.datasets import mnist
(train_X, train_y), (test_X, test_Y) = mnist.load_data()

In [0]:
from tensorflow.keras.utils import to_categorical

X_train = train_X.reshape(60000,28*28)
X_test = test_X.reshape(test_X.shape[0],test_X.shape[1]*test_X.shape[2])
X_train = X_train.astype('float')/255
X_test = X_test.astype('float')/255

y_train = to_categorical(train_y)
y_test = to_categorical(test_Y)

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


Model07 = Sequential()
Model07.add(Dense(512, activation = 'relu', input_dim = 28*28))
Model07.add(Dense(10, activation = 'softmax'))
Model07.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])

In [0]:
Model07.fit(X_train, y_train, epochs = 5, batch_size = 128)

Epoch 1/5
469/469 [==============================] - 2s 4ms/step - loss: 0.2575 - accuracy: 0.9262
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.1037 - accuracy: 0.9698
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0684 - accuracy: 0.9795
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0492 - accuracy: 0.9853
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0371 - accuracy: 0.9887


In [0]:
Model_weight = Model07.get_weights()

In [0]:
Model_weight

[array([[ 0.036596  ,  0.06452872,  0.05339182, ..., -0.06378649,
         -0.05624551,  0.01638282],
        [-0.03010538, -0.06723689, -0.02876402, ...,  0.05921505,
          0.02089267,  0.00080787],
        [ 0.06696784, -0.04385066, -0.00154974, ..., -0.01331782,
          0.01957015, -0.01127635],
        ...,
        [-0.02916649,  0.01821515, -0.06097851, ..., -0.00619907,
          0.02573877, -0.06790241],
        [ 0.06724982, -0.00743985, -0.00769649, ..., -0.02321668,
          0.00581476, -0.02039791],
        [ 0.04272271, -0.05921412,  0.05062024, ...,  0.01105798,
          0.00703216, -0.06410998]], dtype=float32),
 array([ 2.17215866e-02,  2.90245228e-02, -3.89807113e-02, -2.82339286e-02,
         2.86830263e-03,  1.43286601e-01,  1.70235299e-02, -2.84220055e-02,
         1.27065405e-02, -6.53939098e-02, -8.11776668e-02, -2.68211942e-02,
         2.16564499e-02, -3.34608741e-02,  2.52553653e-02,  9.15542431e-03,
        -1.82031784e-02, -5.44107370e-02, -2.03026440e

In [0]:
Model07.save_weights('Model_weight')

In [0]:
Model07_config = Model07.get_config()

In [0]:
from tensorflow.keras.models import Sequential

Model08 = Sequential.from_config(Model07_config)

In [0]:
Model08.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_29 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_30 (Dense)             (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [0]:
Model08.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])

In [0]:
Model08.set_weights(Model_weight)

In [0]:
Model08.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [0]:
Model08.load_weights('Model_weight')

In [0]:
Model08.predict_classes(X_test)

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [0]:
from tensorflow.keras.models import Sequential

Model09 = Sequential.from_config(Model07_config)

In [0]:
from tensorflow.keras import optimizers

sgd_new = optimizers.SGD(learning_rate = 0.5, momentum = 0.9)

Model08.compile(loss = 'categorical_crossentropy', optimizer = sgd_new, metrics = ['accuracy'])

In [0]:
Model08.fit(X_train, y_train, epochs = 5, batch_size = 128)

Epoch 1/5
469/469 [==============================] - 1s 3ms/step - loss: 0.2494 - accuracy: 0.9342
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.2105 - accuracy: 0.9463
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1884 - accuracy: 0.9527
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1810 - accuracy: 0.9569
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1481 - accuracy: 0.9647


In [0]:
Model08.evaluate(X_test, y_test)

313/313 [==============================] - 0s 762us/step - loss: 0.2020 - accuracy: 0.9587


[0.20201005041599274, 0.9587000012397766]

In [0]:
from tensorflow.keras.datasets import imdb

(train_X, train_y), (test_X, test_y) = imdb.load_data(num_words = 1200)

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer

TKObject = Tokenizer(num_words = 1200)

In [0]:
X_train = TKObject.sequences_to_matrix(train_X)

In [0]:
X_test = TKObject.sequences_to_matrix(test_X)

In [0]:
y_train = train_y.astype('float')
y_test = test_y.astype('float')

In [0]:
from tensorflow.keras.models import Sequential

Model09 = Sequential()

In [0]:
from tensorflow.keras.layers import Dense

Model09.add(Dense(32, activation = 'relu', input_dim = 1200))
Model09.add(Dense(16, activation = 'relu'))
Model09.add(Dense(8, activation = 'relu'))
Model09.add(Dense(1, activation = 'sigmoid'))

In [0]:
Model09.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = 'accuracy')

In [0]:
Model09.fit(X_train, y_train, epochs = 10, batch_size = 128, validation_split = 0.1)

Epoch 1/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0760 - accuracy: 0.9776 - val_loss: 0.6256 - val_accuracy: 0.8404
Epoch 2/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0646 - accuracy: 0.9817 - val_loss: 0.6535 - val_accuracy: 0.8416
Epoch 3/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0508 - accuracy: 0.9864 - val_loss: 0.7543 - val_accuracy: 0.8304
Epoch 4/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0469 - accuracy: 0.9866 - val_loss: 0.8971 - val_accuracy: 0.8248
Epoch 5/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0403 - accuracy: 0.9887 - val_loss: 0.8535 - val_accuracy: 0.8312
Epoch 6/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0334 - accuracy: 0.9908 - val_loss: 0.8887 - val_accuracy: 0.8316
Epoch 7/10
176/176 [==============================] - 0s 2ms/step - loss: 0.0322 - accuracy: 0.9911 - val_loss: 1.0075 - val_accuracy: 0.8228
Epoch 